modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      #valid_http_versions: [ "HTTP/1.1", "HTTP/2" ]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      preferred_ip_protocol: "ip4" # or "ip6"
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
          insecure_skip_verify: true
  http_403:
    prober: http
    timeout: 10s
    http:
      #valid_http_versions: [ "HTTP/1.1", "HTTP/2" ]
      valid_status_codes: [403]  # Defaults to 2xx
      method: GET
      preferred_ip_protocol: "ip4" # or "ip6"
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
          insecure_skip_verify: true